version: "3.9"
services:
  app:
    image: agentzhao/reactdocker:latest
    container_name: reactdocker
    build:
      context: ./
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules #empty mount to not overwrite node_modules
    environment:
      - NODE_ENV="development"
